#!/usr/bin/env bash
#
# One-command start for the Wikipedia Edit-Triage Agent.
#
# Brings the whole stack up with a single command, WarpStream-demo style:
#   ./start.sh
#
# It is intentionally idempotent and self-healing:
#   - verifies Docker is installed and running,
#   - seeds .env from .env.example on first run,
#   - on Apple Silicon, auto-detects a reachable host-native Ollama and points
#     Connect at it (the containerized model can crash under Colima/VZ),
#   - starts the stack, waits for the dashboard to report healthy,
#   - opens the dashboard and prints the useful URLs.
#
# Env knobs (all optional):
#   AGENTIC_NO_OPEN=1     don't open a browser at the end
#   AGENTIC_NO_WAIT=1     don't block waiting for health (just `up -d` and exit)
#   AGENTIC_TIMEOUT=180   seconds to wait for the dashboard to come healthy

set -euo pipefail

# Resolve the repo root (the directory this script lives in) so the command
# works from anywhere, including the `curl | bash` installer path.
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_DIR"

DASHBOARD_URL="http://localhost:8080"
CONSOLE_URL="http://localhost:8090"
TIMEOUT="${AGENTIC_TIMEOUT:-180}"

# --- tiny logging helpers --------------------------------------------------
if [ -t 1 ]; then
  BOLD=$'\033[1m'; DIM=$'\033[2m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'
  RED=$'\033[31m'; CYAN=$'\033[36m'; RESET=$'\033[0m'
else
  BOLD=""; DIM=""; GREEN=""; YELLOW=""; RED=""; CYAN=""; RESET=""
fi
info()  { printf '%s\n' "${CYAN}==>${RESET} $*"; }
ok()    { printf '%s\n' "${GREEN}  ok${RESET} $*"; }
warn()  { printf '%s\n' "${YELLOW}  ! ${RESET} $*"; }
die()   { printf '%s\n' "${RED}error:${RESET} $*" >&2; exit 1; }

# --- preflight -------------------------------------------------------------
preflight() {
  info "Preflight checks"

  command -v docker >/dev/null 2>&1 \
    || die "Docker is not installed. Install Docker Desktop: https://docs.docker.com/get-docker/"

  if ! docker info >/dev/null 2>&1; then
    die "Docker is installed but not running. Start Docker Desktop (or your engine) and re-run."
  fi
  ok "Docker is running"

  # `docker compose` (v2) is required; the legacy `docker-compose` is not enough.
  if ! docker compose version >/dev/null 2>&1; then
    die "Docker Compose v2 not found. Update Docker Desktop or install the compose plugin."
  fi
  ok "Docker Compose v2 available"
}

# --- .env seeding ----------------------------------------------------------
seed_env() {
  if [ -f .env ]; then
    ok ".env present"
    return
  fi
  if [ -f .env.example ]; then
    cp .env.example .env
    ok "Seeded .env from .env.example (all defaults; edit it to customize)"
  else
    warn "No .env.example found; relying on docker-compose defaults"
  fi
}

# --- generate a local DB password ------------------------------------------
# Don't ship the well-known `change-me` default for a fresh local run. CRITICAL:
# Postgres only applies POSTGRES_PASSWORD on the FIRST init of an empty data
# volume — it ignores it on an existing volume. So we only generate a password
# when there is NO pgdata volume yet; otherwise we must leave the credential
# alone (changing it would make every service fail auth against the old volume).
ensure_db_password() {
  if docker volume ls --format '{{.Name}}' 2>/dev/null | grep -q '_pgdata$'; then
    if grep -qE '^[[:space:]]*POSTGRES_PASSWORD=' .env 2>/dev/null; then
      ok "Existing DB volume + POSTGRES_PASSWORD in .env (kept; must match the volume)"
    else
      ok "Existing DB volume detected; keeping its baked-in password"
    fi
    warn "If you see 'password authentication failed', the .env password and the"
    warn "existing DB volume disagree — run 'docker compose down -v' to re-init."
    return
  fi
  if grep -qE '^[[:space:]]*POSTGRES_PASSWORD=' .env 2>/dev/null; then
    ok "POSTGRES_PASSWORD configured in .env (fresh volume will use it)"
    return
  fi
  local pw
  pw="$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom 2>/dev/null | head -c 24 || true)"
  [ -z "$pw" ] && pw="local-$(date +%s)"
  printf '\n# Auto-generated by start.sh on first run (local dev credential).\nPOSTGRES_PASSWORD=%s\n' "$pw" >> .env
  ok "Generated a random POSTGRES_PASSWORD into .env (fresh volume)"
}

# --- Apple Silicon / host-Ollama auto-detect -------------------------------
# The containerized Ollama can crash during inference on arm64 Colima VMs. If
# the user is on Apple Silicon AND a host-native Ollama is already answering on
# :11434, prefer it automatically (fast, GPU-accelerated). Otherwise leave the
# compose default (containerized Ollama) untouched.
detect_ollama() {
  local arch host_ollama="http://localhost:11434"
  arch="$(uname -m 2>/dev/null || echo unknown)"

  # Respect an explicit user choice.
  if [ -n "${OLLAMA_ADDRESS:-}" ]; then
    ok "Using OLLAMA_ADDRESS from environment: ${OLLAMA_ADDRESS}"
    return
  fi
  if grep -qE '^[[:space:]]*OLLAMA_ADDRESS=' .env 2>/dev/null; then
    ok "Using OLLAMA_ADDRESS from .env"
    return
  fi

  if [ "$arch" = "arm64" ] && [ "$(uname -s)" = "Darwin" ]; then
    if curl -fsS --max-time 2 "${host_ollama}/api/tags" >/dev/null 2>&1; then
      info "Apple Silicon + reachable host Ollama detected"
      printf '\n# Auto-added by start.sh: use the host-native Ollama (GPU, stable on arm64).\nOLLAMA_ADDRESS=http://host.docker.internal:11434\n' >> .env
      ok "Pointed Connect at host Ollama (http://host.docker.internal:11434)"
    else
      warn "Apple Silicon detected but no host Ollama on :11434."
      warn "If the containerized model crashes, run 'brew install ollama && ollama serve'"
      warn "then 'ollama pull llama3.2' and re-run ./start.sh."
    fi
  fi
}

# --- bring the stack up ----------------------------------------------------
# `--build` ensures the app image is rebuilt when dependencies change (e.g. a
# new requirement like alembic), so `up` never reuses a stale cached image.
compose_up() {
  info "Starting the stack (docker compose up -d --build)"
  docker compose up -d --build --remove-orphans
  ok "Containers started"
}

# --- wait for health -------------------------------------------------------
wait_for_health() {
  if [ "${AGENTIC_NO_WAIT:-0}" = "1" ]; then
    warn "AGENTIC_NO_WAIT=1 set; not waiting for health"
    return
  fi
  info "Waiting for the dashboard to come healthy (up to ${TIMEOUT}s)"
  local waited=0
  until curl -fsS --max-time 3 "${DASHBOARD_URL}/healthz" >/dev/null 2>&1; do
    sleep 3
    waited=$((waited + 3))
    if [ "$waited" -ge "$TIMEOUT" ]; then
      warn "Dashboard not healthy after ${TIMEOUT}s."
      warn "Check logs with: docker compose logs -f webapp"
      return
    fi
    printf '%s' "${DIM}.${RESET}"
  done
  printf '\n'
  ok "Dashboard is healthy"
}

# --- open browser ----------------------------------------------------------
open_dashboard() {
  [ "${AGENTIC_NO_OPEN:-0}" = "1" ] && return
  if command -v open >/dev/null 2>&1; then
    open "$DASHBOARD_URL" >/dev/null 2>&1 || true
  elif command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$DASHBOARD_URL" >/dev/null 2>&1 || true
  fi
}

main() {
  printf '%s\n' "${BOLD}Wikipedia Edit-Triage Agent — one-command start${RESET}"
  preflight
  seed_env
  ensure_db_password
  detect_ollama
  compose_up
  wait_for_health
  open_dashboard
  printf '\n%s\n' "${BOLD}Ready.${RESET}"
  printf '  %sDashboard%s  %s\n' "$BOLD" "$RESET" "$DASHBOARD_URL"
  printf '  %sConsole%s    %s\n' "$BOLD" "$RESET" "$CONSOLE_URL"
  printf '\n%sThe dashboard shows seeded rows until live edits arrive (first model\n' "$DIM"
  printf 'pull + diff fetch take a minute). Follow along with: make logs-connect%s\n' "$RESET"
  printf '%sStop everything with: docker compose down  (or: make down)%s\n' "$DIM" "$RESET"
}

main "$@"
